#!/bin/bash
source ./.githooks/colors.sh

npm run build && npm run deepdocs

re="README"
files=`git status -s | grep "$re" | cut -c4-`
code=`git status -s | grep "$re" | cut -c1- | head -c 1`

if [ ! -z "$files" ] && [ "$code" != "D" ]
then
  `git add $files`
  echo "${green}Adding README files${no_color}"
fi
