#!/bin/bash
source ./.githooks/colors.sh

registry_url=`grep -o 'registry=.*$' .npmrc`
registry_prefix="registry=(.*)"
while [[ $registry_url =~ $registry_prefix ]]; do
  registry_url=${BASH_REMATCH[1]}
done

files=`git diff --cached --name-status`
re="package.json"
if [[ $files =~ $re ]]
then
  npm prune
  npm shrinkwrap
  node_modules/.bin/rewrite-shrinkwrap-urls -r $registry_url -p
  git add npm-shrinkwrap.json
  echo "${green}Adding npm-shrinkwrap.json${no_color}"
fi
