toc:
  - name: Build
    description: |
      Command to recursively extract documentation comments and build
      *README.md* files at each folder level.
  - init
  - write
  - getDirectories
  - handler
