toc:
  #main
  - name: Deepdocs
    description: |
      Create README files in every folder containing documentation comments.
  #docs
  - name: Utils
    description: |
      Set of helper functions that facilitate the work of the library commands.
  - getDirectories
  - directoriesFilter
  - getFiles
  - filesFilter
  - filePath
  - hasConfig
  - configTemplate
  - populateConfig
  - ymlCompose

  - name: Build
    description: |
      Command to recursively extract documentation comments and build
      *README.md* files at each folder level.
  - handler
  - init
  - write
